global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9110']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

